Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo config docker swarm cluster"
  config.vm.define "manager" do |manager|
      manager.vm.box = "centos/7"
      manager.vm.hostname = "manager"
      manager.vm.provision "shell", path: "provision.sh"
      manager.vm.network "private_network", ip: "192.168.56.3"
      manager.vm.network "forwarded_port", guest: 80, host: 8080
  end
  config.vm.define "work1" do |work1|
      work1.vm.box = "centos/7"
      work1.vm.hostname = "work1"
      work1.vm.provision "shell", path: "provision.sh"
      work1.vm.network "private_network", ip: "192.168.56.4"
end
  config.vm.define "work2" do |work2|
      work2.vm.box = "centos/7"
      work2.vm.hostname = "work2"
      work2.vm.provision "shell", path: "provision.sh"
      work2.vm.network "private_network", ip: "192.168.56.5"
end

end
